### ISSUE TITLE
Add advanced configuration options for piwik analytics

### ISSUE THREAD

**Issue by ruKurz** [mrsimpson/Rocket.Chat#15]
In order to use one Piwik instance for tracking several sub domains, some advanced piwik configuration options have to be set. This kind of configuration should be part of the administration UI of Rocket.Chat.

This issue implements the following options 

Prepend the site domain to the page title when tracking
  `_paq.push(["setDocumentTitle", document.domain + "/" + document.title]);`
Track visitors across all subdomains
  `_paq.push(["setCookieDomain", "*.your.domain.tld"]);`
In the 'Outlinks' report, hide clicks to known alias URLs
  `_paq.push(["setDomains", ["*.your.domain.tld"]]);`

**Comment by mrsimpson** [comment]
Lgtm. 
Merging later. Please PR to Rocket.Chat fork.

**Comment by ruKurz** [comment]
In https://github.com/RocketChat/Rocket.Chat/issues/233 is shortly discussed why RC won't implement all Piwik Config options. Might be a reason for decline the pull request.
Also I'm not sure if the second commit: https://github.com/mrsimpson/Rocket.Chat/commit/89df55c33f8b0d93d8390b20b9a39ea43e12b915 meets the intend of Piwik. "set a custom URL" leads to incorrect links in Piwik UI. But was the only way I found to tweak the sub domain handling.

**Comment by ruKurz** [comment]
Lessons learned: A piwik website configuration has settings for subdomains. Using this settings makes the commit unnecessary https://github.com/mrsimpson/Rocket.Chat/commit/89df55c33f8b0d93d8390b20b9a39ea43e12b915

@see How do I accurately measure the same visitor across multiple domain names (cross domain linking)? https://piwik.org/faq/how-to/faq_23654/

**Comment by ruKurz** [comment]
Piwik supports tracking the same website into two different piwik instances.
@see The complete guide on tracking your websites and web apps into multiple Piwiks and how to do it easily & efficiently https://piwik.org/blog/2017/02/complete-guide-tracking-websites-web-apps-multiple-piwiks-easily-efficiently/

Would be nice if that would be configureable in Rocket.Chat Analytics Admin UI.
For this feature I will open a new Issue. Posting it here, soon.

**Comment by ruKurz** [comment]
related with https://github.com/mrsimpson/Rocket.Chat/issues/17

**Comment by ruKurz** [comment]
merged and deployed.

**Comment by ruKurz** [comment]
make a pull request to RC core.
