### ISSUE TITLE
Several Knowledge Domains should be useable by one client

### ISSUE THREAD

**Issue by ruKurz** [mrsimpson/Rocket.Chat#24]
It would be great if we could offer the knowledge from one client to another. Imagine the following szenario. We have 2 clients both working in there own knowledge domain, not knowing that there is somebody else using assistify who is currently creating knowledge what will be highly relevant for himself. One day those two clients are drinking some beer and sharing their experiences with assistify and get to know each others activity. In the next morning our phone is ringing and Mr. XY tells that he likes to share his knowledge across the borders of its own domain with Mr. ZZ.

In this case we should make sure, that new knowledge can only be created in the specific domain of one client, but that the approved knowledge can be offered to someone else. Of course the knowledge owner has to commit that.

**Comment by janrudolph** [comment]
@ruKurz Shouldn't we move this issue to Smarti?

**Comment by ruKurz** [comment]
@janrudolph yes, done: https://github.com/assistify/smarti/issues/4
