### ISSUE TITLE
Delete particular conversations from knowledge base

### ISSUE THREAD

**Issue by ruKurz** [mrsimpson/Rocket.Chat#25]
There should be an option to delete conversations of bad quality manually. Most likely this process might be support by our KI part.

Sometimes it occurs that somebody has a problem, but at the end he finds the solution himself.
Sometimes somebody just had a small problem, but dig into a small talk via chat.
Sometimes somebody just asked the wrong person or the problem solves itself.

In all of this szenarios we have a conversation of not very helpful messages.
If all of those message will be part of the knowledge base. These questions will overfill the knowledge base with wrong or not needful information.

There must be a way to simply delete a single conversation from the knowledge base.
Or the Knowledge Base itself is able to decide whether a message is valuable or not.

**Comment by ruKurz** [comment]
On Smarti side this Issue is implemented.
Maybe we want to offer an feature within the Smarti Widget for deleting a message by users.

**Comment by mrsimpson** [comment]
This issue was moved to assistify/smarti#2
