### ISSUE TITLE
Naming a topic channel: Uppercase ist not possible

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#36]
When editing a topic channel's title, uppercase letters are not possible.

**Comment by mrsimpson** [comment]
![Großschreibung.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5964d542d69911001fbe82ef/125516c66e82c728ace21e0d46cf8695807d90aa87fbba4aa648fe936b0a65633b0ba92e7391a172fd1722550a5d47f8125c5715f5afdb2ba6b56a268f0a5fe5d77f4366846c4ff8e7df46f554f832815d87b0b68b49c0e83f22e28d8747381b020ac4.png)

**Comment by mrsimpson** [comment]
Still, no blanks or special characters except -, _, . are accepted

**Comment by janrudolph** [comment]
Creating a channel with uppercase letters works now. Editing an existing Channel does not work.

**Comment by mrsimpson** [comment]
@janrudolph This is not related to uppercase, but related to changing a request channel name, right?
I guess it shouldn't be possible as potential naming conflicts could occur (we have an automated naming in place).

**Comment by janrudolph** [comment]
fixed
