### ISSUE TITLE
Behavior after closing a channel

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#38]
When clicking "Hilfe beenden", most users will be kicked out of the channel. Just the user who closed the room will remain there and does not get any information what has happened to the others. The button "Hilfe beenden" is still in place, the chat window open, the channel writeable....We need a better state which represents the current situation to the user.

**Comment by mrsimpson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assistify.Chat Issue #38: Behavior after closing a channel](https://trello.com/c/39IWWgjV/223-assistifychat-issue-38-behavior-after-closing-a-channel)

**Comment by janrudolph** [comment]
Works fine now. However, we should think about a label "closed conversation: all your colleagues left the room" which is displayed instead of the "Hilfe beenden" button. This would improve the user experience.
