### ISSUE TITLE
Remove black bars beneath "new request dialog"

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#48]
**UI Improvement**
Please remove the black bars beneath the "new request dialog" (see screenshot). 

![requests-black-bars](https://user-images.githubusercontent.com/3596824/28323837-2f97c526-6bda-11e7-86f3-4e611c834e1f.png)

**Comment by ruKurz** [comment]
https://github.com/assistify/Rocket.Chat/issues/44

**Comment by ruKurz** [comment]
@janrudolph please close
