### ISSUE TITLE
Entering a room without subscription creates frontend exception

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/Rocket.Chat#52]
When entering a room which the user is not subscribed to, a frontend exception is raised.
Reason is that the callback which tries to open the tab bar panel expects a subscription as parameter.

**Comment by janrudolph** [comment]
fixed

**Comment by mrsimpson** [comment]
Fixed with https://github.com/mrsimpson/Rocket.Chat/commit/9a8935b01edeac31bad3f2b43fdaeebc669a4b7a
