### ISSUE TITLE
Redirect after first login does not work properly 

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#60]
When a user performs a login the first time, the system asks for a username. The user is then redirected to the home page of Rocket.Chat. 

**Issue**:
If a request channel is created by a third party system (e.g. SAP) and the user has to determine its username at login, a redirect to the request channel is not in place. The user will be redirected to the home page. By this, the system does not create a request channel. The information is lost.

**Possible Solution**:
Redirect and create a new request channel.

**Comment by mrsimpson** [comment]
@janrudolph are you sure no request has been created? It is actually created by a technical user, the room is opened afterwards. The redirect-issue is understood, but the new channel should be there as an unread request room.

**Comment by janrudolph** [comment]
I am not sure. @vickyokrm May you answer Oliver's question please?

**Comment by mrsimpson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assistify.Chat Issue #60: Redirect after first login does not work properly ](https://trello.com/c/FRAazZ3H/373-assistifychat-issue-60-redirect-after-first-login-does-not-work-properly)

**Comment by janrudolph** [comment]
Additional info: Appears only if admin creates new local non SSO user.

**Comment by mrsimpson** [comment]
This issue was moved to assistify/Rocket.Chat#22
