### ISSUE TITLE
Chat message send icon was not refreshed

### ISSUE THREAD

**Issue by vickyokrm** [mrsimpson/Rocket.Chat#62]
**Overview**
The chat message send icon was not updated after the result was copied from the search.

**Issue Statement:**
When the chat user select a message from the search result, the message will be copied to the message window awaiting the user to click to send the message. The icon for the send message was not change to send icon but it shows attach icon instead.

**Comment by mrsimpson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assistify.Chat Issue #62: Chat message send icon was not refreshed](https://trello.com/c/K6USi1xi/374-assistifychat-issue-62-chat-message-send-icon-was-not-refreshed)

**Comment by mrsimpson** [comment]
Fixed on Assistify-side - PR towards RC is a new issue
