### ISSUE TITLE
Rocket.Chat Plugin: Rename button "Hilfe beenden" 

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#69]
**Issue**
When closing a request / livechat, one user will use the button "Hilfe beenden". The button will close the room. However, a user might think that pressing the button will just close the knowledge base and not the room(feedback from real user).

**Solution**
Rename the button in "Chat beenden".

**Comment by mrsimpson** [comment]
Fixed with ef24209ca
