### ISSUE TITLE
Canceling the termination of a conversation does not work

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#70]
A conversation is finished (livechat, request). The user likes to terminate the conversation. But the user realizes that there is an additional question. Therefore the user cancels the termination dialog.

**Issue**
It is not possible to cancel the termination dialog. The conversation is closed when pressing the button "Hilfe beenden".

**Solution**
Terminate conversation when user confirms the popup.

**Comment by ruKurz** [comment]
Is this a custom issue or is this a general rocket.chat issue?

**Comment by mrsimpson** [comment]
This issue was moved to assistify/Rocket.Chat#3
