### ISSUE TITLE
Role-based requests

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#91]
Currently users are able to create requests for all available topics. However, this is not favorable in every situation. Imagine a team connects with external partners. The external partners should not be able to create requests for every topic. There might just be some topics which are relevant for the external partners. 

Preventing access to every topic helps to solve issue https://github.com/redlink-gmbh/smarti/issues/21 . We could focus on filters there.

**Comment by ruKurz** [comment]
@janrudolph should we move this issue to assistify?

**Comment by janrudolph** [comment]
Moved to https://github.com/assistify/Rocket.Chat/issues/61
