### ISSUE TITLE
Live-Chat messages sent short before the opening hours will be closed, can't be answered afterwards

### ISSUE THREAD

**Issue by ruKurz** [mrsimpson/Rocket.Chat#93]
Reported by HMP

ANALYSE: Öffnungszeiten: 16:58 kommt ne Nachricht rein, die kann ab 17:00 nicht mehr beantworten

**Comment by janrudolph** [comment]
Is this really a bug, or just a straight implementation of the feature?

**Comment by janrudolph** [comment]
@ruKurz please close issue.
