### ISSUE TITLE
Live-Chat conversation close dialog should be customizable

### ISSUE THREAD

**Issue by ruKurz** [mrsimpson/Rocket.Chat#95]
When closing a live-chat conversation, a dialog comes up that allows to insert a plain text message. For agent reporting purpose it would be nice to have a form here, that allows to categorize and add some meta data.

**Comment by janrudolph** [comment]
duplicate to https://github.com/mrsimpson/Rocket.Chat/issues/71

**Comment by mrsimpson** [comment]
duplicate, closed

**Comment by mrsimpson** [comment]
This issue was moved to assistify/Rocket.Chat#14
